# Generated by Django 5.1.7 on 2025-04-25 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIUApp', '0003_user_avatar_alter_user_bio_alter_user_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='github',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='linkedin',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='stackoverflow',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='twitter',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
