# Generated by Django 5.1.7 on 2025-04-26 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AIUApp', '0004_user_github_user_linkedin_user_stackoverflow_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='experience',
            field=models.TextField(blank=True, help_text='Describe projects, internships, or work experience', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='goals',
            field=models.TextField(blank=True, help_text='Describe your learning goals and areas to improve', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, help_text='List of skills, separated by commas (e.g. Python, Django, React)', null=True),
        ),
    ]
