# Generated by Django 5.1.1 on 2024-11-03 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIUApp', '0005_alter_room_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['updated', 'created']},
        ),
    ]
