# Generated by Django 5.1.7 on 2025-04-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AIUApp', '0007_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
